workflows:
  hello-world:
    name: Hello world workflow
    instance_type: mac_pro
    max_build_duration: 100
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
      vars:
        GOOGLE_PLAY_TRACK: "beta"
      flutter: stable
      xcode: latest
      cocoapods: 1.9.1
      node: 12.14.0
      npm: 6.13.7
      ndk: r21d
      java: 1.8
      ruby: 2.7.2
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
        - pattern: develop
          include: false
    scripts:
      - name: Get Flutter Packages
        script: flutter package pub get
      - name: Build apk
        script: flutter build apk --release
      - name: Build ios
        script: flutter build ios